#!/usr/bin/env node

const { Migrate, ModelComponent, ControllerComponent,
  MigrationComponent, JobLoader, Structure } = require("brainpi");

var command;
var param_1;
var param_2;
process.argv.forEach((val, index) => {
  if (index == 2) {
    command = val;
  }
  if (index == 3) {
    param_1 = val;
  }
  if(index == 4) {
    param_2 = val;
  }
});


switch(command)
{
  case "migrate":
      Migrate.migrate();
      break;
  case "create:controller":
      if(param_1 != null) {
        return ControllerComponent(param_1);
      } else {
        console.log("ERROR: Missing Parameter For Controller Name!");
        console.log("Closing Conduct...");
        process.exit();
      }
  case "create:model":
      if(param_1 != null) {
        if(param_2 != null) {
          return ModelComponent(param_1, param_2);
        }
        else
          return ModelComponent(param_1, '""');
      } else {
        console.log("ERROR: Missing Parameter For Model Name!");
        console.log("Closing Conduct...");
        process.exit();
      }
  case "make:migration":
      if(param_1 != null) {
        if(param_2 != null) {
          return MigrationComponent(param_1, param_2);
        }
        else
          return MigrationComponent(param_1, '""');
      } else {
        console.log("ERROR: Missing Parameter For Migration Name!");
        console.log("Closing Conduct...");
        process.exit();
      }
  case "cron:start": {
    if(param_1 != null) {
      return JobLoader.loadSingle( param_1 );
    } else {
      console.log("ERROR: Missing Job Name Paramerter!");
      console.log("Closing Conduct...");
      process.exit();
    }
  }
  case "link": {
    if(param_1 == null || param_2 == null) {
      console.log("ERROR: Missing Required Parameter(s)!");
      console.log("Closing Conduct...");
      process.exit();
    }

    return Structure.link(param_1, param_2);

  }
  case "filesystem:public": {
    if(param_1 == null) {
      param_1 = "storage/public";
    }

    if(param_2 == null) {
      param_2 = "public/files"
    }

    return Structure.link(param_1, param_2);

  }
  default:
      console.log("Unknown Parameter: "+x);
      process.exit();
}